# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d9611bde37995e77b2a9994fdaf301dc25e4bf28a6b9f20936151f3f35750d3bd14049b68befc9d18b93026ff98112814c3bb51c983898d29deb4ae34d2822c

test:
  secret_key_base: d7902d2b38b8e7993c93e5353ed573e23ac7ac4d4ef2ad43a6d8c6675a3b0028f4e40f6f77f3e7d73facd3e914aee3fee64d6ea5f5af8f51aa2a2113071c7df2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
